POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvbG9uZWMiLCJpZCI6IjY3M2NiNzcwNGM4YmZjMjMyYTcxYTJmZSIsImlhdCI6MTczMjA0OTUxMywiZXhwIjoxNzMyMDQ5NTQzfQ.P7rFSbXH3MDIxSWC_1p33yYf5FJmU038Qg3qLWi2cvE

{
    "content": "Poznamka prihlaseneho Paliho s tokenom exp",
    "important": true,
    "userId": "673cb7704c8bfc232a71a2fe"
    
}