DELETE http://localhost:3003/api/blogs/673dddc2d023a1dbe85b4385
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvbG9uZWMiLCJpZCI6IjY3M2RhMjkyYjhmNzgzNTIyMGZhOGEwMCIsImlhdCI6MTczMjEwNTk2NSwiZXhwIjoxNzMyMTA5NTY1fQ.3CW1MxvBX4_38QkFkmo4cQ_Y3O0IS6qtSC-U6sG2z0I
